import { Menu } from "@headlessui/react";
import Cookies from "js-cookie";
import { signOut, useSession } from "next-auth/react";
import Head from "next/head";
import Link from "next/link";
import { useContext, useEffect, useState } from "react";
import { ToastContainer } from "react-toastify";

import { DropdownLink } from ".";
import { ACTIONS, Store } from "../utils";

export const Layout = ({ title, children }) => {
  const { status, data: session } = useSession();
  const { state, dispatch } = useContext(Store);
  const { cart } = state;
  const [cartItemsCount, setItemCount] = useState(0);
  useEffect(() => {
    setItemCount(cart.cartItems.reduce((a, c) => a + c.quantity, 0));
  }, [cart.cartItems]);

  const logoutHandler = () => {
    Cookies.remove("cart");
    dispatch({ type: ACTIONS.CART_RESET });
    signOut({ callbackUrl: "/login" });
  };

  return (
    <div>
      <Head>
        <title>{title ? title + " - Amazonka" : "Amazonka"}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <ToastContainer position="bottom-center" limit={1} />

      <div className="flex min-h-screen flex-col">
        <header>
          <nav className="flex items-center justify-between shadow-md h-10 px-5">
            <Link href="/">
              <a className="text-lg font-bold">Amazonka</a>
            </Link>
            <div>
              <Link href="/cart">
                <a className="p-2">
                  Cart
                  {cartItemsCount > 0 && (
                    <span className="badge">{cartItemsCount}</span>
                  )}
                </a>
              </Link>
              {status === "loading" ? (
                "Loading"
              ) : session?.user ? (
                <Menu as="div" className="relative inline-block">
                  <Menu.Button>{session.user.name}</Menu.Button>
                  <Menu.Items className="menu-item">
                    {session.user.isAdmin && (
                      <>
                        <DropdownLink className="dropdown-link" href="/users">
                          Users
                        </DropdownLink>
                        <DropdownLink
                          className="dropdown-link"
                          href="/admin/products"
                        >
                          Products
                        </DropdownLink>
                        <DropdownLink
                          className="dropdown-link"
                          href="/orders/list"
                        >
                          <a href="#" onClick={logoutHandler}>
                            Orders list
                          </a>
                        </DropdownLink>
                        <hr />
                      </>
                    )}
                    <DropdownLink className="dropdown-link" href="/profile">
                      Profile
                    </DropdownLink>
                    <DropdownLink
                      className="dropdown-link"
                      href="/orders/history"
                    >
                      Orders history
                    </DropdownLink>
                    <DropdownLink className="dropdown-link" href="/login">
                      <a href="#" onClick={logoutHandler}>
                        Logout
                      </a>
                    </DropdownLink>
                  </Menu.Items>
                </Menu>
              ) : (
                <Link href="/login">
                  <a className="p-2">Login</a>
                </Link>
              )}
            </div>
          </nav>
        </header>
        <main className="flex-grow container m-auto px-5 pt-5">{children}</main>
        <footer className="flex justify-center items-center h-10 shadow-inner">
          Copyright &copy; Amazonka {new Date().getFullYear()}
        </footer>
      </div>
    </div>
  );
};
