import bcrypt from "bcryptjs";

export const data = {
  users: [
    {
      name: "John",
      email: "admin@example.com",
      password: bcrypt.hashSync("12345"),
      isAdmin: true,
    },
    {
      name: "Jane",
      email: "user@example.com",
      password: bcrypt.hashSync("12345"),
      isAdmin: false,
    },
  ],

  products: [
    {
      name: "Hourglass chino trousers in stone",
      slug: "Hourglass-chino-trousers-in-stone",
      category: "Clothing",
      image: "/images/p4.jpg",
      price: 382,
      brand: "ASOS",
      rating: 4,
      numReviews: 160,
      countInStock: 4,
      description:
        "Chino trousers by ASOS DESIGN, For when you mean business, Concealed fly, Side pockets and two back pockets, Slim fit, A narrow cut that sits close to the body",
    },
    {
      name: "Shacket in blue",
      slug: "shacket-in-blue",
      category: "Sporting Goods",
      image: "/images/p2.jpg",
      price: 629,
      brand: "Gianni Feraud",
      rating: 4,
      numReviews: 102,
      countInStock: 5,
      description:
        "Shacket by Gianni Feraud, For unpredictable weather conditions, Spread collar, Button placket, Functional pockets, Regular fit, True to size",
    },
    {
      name: "Slim fit grandad shirt",
      slug: "slim-fit-grandad-shirt",
      category: "Clothing",
      image: "/images/p3.jpg",
      price: 136,
      brand: "Bolongaro",
      rating: 3,
      numReviews: 130,
      countInStock: 7,
      description:
        "Grandad shirt by Bolongaro Trevor, For when you mean business, Button-down collar, Button placket, Chest pocket, Slim fit, A narrow cut that sits close to the body",
    },
    {
      name: "T-shirt in cashmere blue",
      slug: "t-shirt-in-cashmere-blue",
      category: "Clothing",
      image: "/images/p5.jpg",
      price: 746,
      brand: "Jack&Jones",
      rating: 5,
      numReviews: 80,
      countInStock: 8,
      description:
        "T-shirt by Jack Jones, Crew neck, Short sleeves, Regular fit, True to size",
    },
    {
      name: "Studded short",
      slug: "studded-short",
      category: "Sporting Goods",
      image: "/images/p1.jpg",
      price: 114,
      brand: "Miss Selfridge",
      rating: 3,
      numReviews: 10,
      countInStock: 7,
      description:
        "Shorts by Miss Selfridge, For when you mean business, High-rise waist, Zip fly, Functional pockets, Studded detail, Regular fit, True to size",
    },
    {
      name: "Mensy peg trouser in sand",
      slug: "mensy-peg-trouser-in-sand",
      category: "Clothing",
      image: "/images/p6.jpg",
      price: 199,
      brand: "Topshop",
      rating: 4,
      numReviews: 19,
      countInStock: 5,
      description:
        "Peg trousers by Topshop, For when you mean business, High-rise waist, Zip fly, Functional pockets, Peg leg, Regular fit, True to size",
    },
    {
      name: "Gdansk shirt in white",
      slug: "gdansk-shirt-in-white",
      category: "Clothing",
      image: "/images/p77.jpg",
      price: 242,
      brand: "Burton",
      rating: 4,
      numReviews: 12,
      countInStock: 6,
      description:
        "Shirt by Burton Menswear London, For when you mean business, Point collar, Button placket, Chest pocket, Regular fit, True to size",
    },
    {
      name: "Quilted jacket in black",
      slug: "quilted-jacket-in-black",
      category: "Clothing",
      image: "/images/p8.jpg",
      price: 912,
      brand: "Jack&Jones",
      rating: 4,
      numReviews: 14,
      countInStock: 3,
      description:
        "Yield jacket by Jack Jones, For unpredictable weather conditions, Funnel neck, Zip fastening, Functional pockets, Regular fit, True to size",
    },
    {
      name: "Polo shirt in white",
      slug: "polo-shirt-in-white",
      category: "Clothing",
      image: "/images/p9.jpg",
      price: 100,
      brand: "Quiksilver",
      rating: 5,
      numReviews: 15,
      countInStock: 2,
      description:
        "Polo shirt by Quiksilver, Polo collar, Button placket, Short sleeves, Regular fit, True to size",
    },
    {
      name: "Ripped jeans in black",
      slug: "ripped-jeans-in-black",
      category: "Clothing",
      image: "/images/p10.jpg",
      price: 777,
      brand: "New Look",
      rating: 3,
      numReviews: 16,
      countInStock: 11,
      description:
        "Ripped jeans by New Look, For when you mean business, High-rise waist, Concealed fly, Functional pockets, Ripped knees, Slim fit, A narrow cut that sits close to the body",
    },
  ],
};
