import bcrypt from "bcryptjs";

export const data = {
  users: [
    {
      name: "John",
      email: "admin@example.com",
      password: bcrypt.hashSync("12345"),
      isAdmin: true,
    },
    {
      name: "Jane",
      email: "user@example.com",
      password: bcrypt.hashSync("12345"),
      isAdmin: false,
    },
  ],

  products: [
    {
      name: "Studded short",
      slug: "studded-short",
      price: "114.00",
      brand: "Miss Selfridge",
      rating: 3,
      numReviews: 10,
      countInStock: 7,
      description: "The Intelligent Concrete Chair is an excellent product.",
      image: "/images/p1.jpg",
    },
    {
      name: "Shacket in blue",
      slug: "shacket-in-blue",
      price: "629.00",
      brand: "Gianni Feraud",
      rating: 4,
      numReviews: 102,
      countInStock: 5,
      description: "  The Incredible Soft Salad is an excellent product.",
      image: "/images/p2.jpg",
    },
    {
      name: "Slim fit grandad shirt",
      slug: "slim-fit-grandad-shirt",
      price: "136.00",
      brand: "Bolongaro",
      rating: 3,
      numReviews: 130,
      countInStock: 7,
      description: "The Unbranded Concrete Salad is an excellent product.",
      image: "/images/p3.jpg",
    },
    {
      name: "Hourglass chino trousers in stone",
      slug: "Hourglass-chino-trousers-in-stone",
      price: "382.00",
      brand: "ASOS",
      rating: 4,
      numReviews: 160,
      countInStock: 4,
      description: "The Tasty Metal Gloves is an excellent product.",
      image: "/images/p4.jpg",
    },
    {
      name: "T-shirt in cashmere blue",
      slug: "t-shirt-in-cashmere-blue",
      price: "746.00",
      brand: "Jack&Jones",
      rating: 5,
      numReviews: 80,
      countInStock: 8,
      description: "The Handcrafted Wooden Mouse is an excellent product.",
      image: "/images/p5.jpg",
    },
    {
      name: "Mensy peg trouser in sand",
      slug: "mensy-peg-trouser-in-sand",
      price: "199.00",
      brand: "Topshop",
      rating: 4,
      numReviews: 19,
      countInStock: 5,
      description: "The Ergonomic Plastic Pants is an excellent product.",
      image: "/images/p6.jpg",
    },
  ],
};
