export const data = [
  {
    color: "grey",
    department: "Sports",
    name: "Intelligent Concrete Chair",
    slug: "intelligent-concrete-chair",
    price: "114.00",
    brand: "Nike",
    rating: 3,
    numReviews: 10,
    countInStock: 0,
    description: "The Intelligent Concrete Chair is an excellent product.",
    image: "/images/p1.jpg",
  },
  {
    color: "olive",
    department: "Garden",
    name: "Incredible Soft Salad",
    slug: "incredible-soft-salad",
    price: "629.00",
    brand: "Nike",
    rating: 4,
    numReviews: 102,
    countInStock: 5,
    description: "  The Incredible Soft Salad is an excellent product.",
    image: "/images/p2.jpg",
  },
  {
    color: "black",
    department: "Electronics",
    name: "Unbranded Concrete Salad",
    slug: "unbranded-concrete-salad",
    price: "136.00",
    brand: "Nike",
    rating: 3,
    numReviews: 130,
    countInStock: 4,
    description: "The Unbranded Concrete Salad is an excellent product.",
    image: "/images/p3.jpg",
  },
  {
    color: "teal",
    department: "Electronics",
    name: "Tasty Metal Gloves",
    slug: "tasty-metal-gloves",
    price: "382.00",
    brand: "Nike",
    rating: 4,
    numReviews: 160,
    countInStock: 1,
    description: "The Tasty Metal Gloves is an excellent product.",
    image: "/images/p4.jpg",
  },
  {
    color: "sky blue",
    department: "Movies",
    name: "Handcrafted Wooden Mouse",
    slug: "handcrafted-wooden-mouse",
    price: "746.00",
    brand: "Nike",
    rating: 5,
    numReviews: 80,
    countInStock: 2,
    description: "The Handcrafted Wooden Mouse is an excellent product.",
    image: "/images/p5.jpg",
  },
  {
    color: "white",
    department: "Home",
    name: "Ergonomic Plastic Pants",
    slug: "ergonomic-plastic-pants",
    price: "199.00",
    brand: "Nike",
    rating: 4,
    numReviews: 19,
    countInStock: 5,
    description: "The Ergonomic Plastic Pants is an excellent product.",
    image: "/images/p6.jpg",
  },
];
